disabled_rules:
  - line_length
  - type_body_length
  - file_length
  - no_fallthrough_only
  - no_space_in_method_call
  - opening_brace
  - operator_whitespace
  - trailing_comma
  - trailing_whitespace
  - valid_ibinspectable

# commented out rules can be uncommented upon adoption of SwiftLint >= 0.47.0
opt_in_rules:
#  - accessibility_label_for_image
  - anonymous_argument_in_multiline_closure
  - array_init
  - closure_body_length
  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_none_name
  - empty_collection_literal
  - empty_string
#  - empty_xctest_method
  - enum_case_associated_values_count
  - explicit_init
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_objc_type
  - let_var_whitespace
#  - missing_docs
  - multiline_function_chains
  - object_literal
  - optional_enum_case_matching
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
#  - return_value_from_void_function
  - sorted_first_last
  - static_operator
  - test_case_accessibility
  - toggle_bool
  - trailing_closure
#  - typesafe_array_init
  - unavailable_function
  - untyped_error_in_catch
  - xct_specific_matcher

analyzer_rules:
  - unused_import
  - unused_declaration
  
conditional_returns_on_newline:
  if_only: true

closure_body_length:
  warning: 40

unused_declaration:
  include_public_and_open: true

identifier_name:
  max_length: 60

closure_body_length:
  warning: 60
